
plugins {
    id 'java'
    id 'eclipse' // optional (to generate Eclipse project files)
    id 'idea' // optional (to generate IntelliJ IDEA project files)
}

repositories {
    mavenCentral()
}

dependencies {

    testImplementation('org.seleniumhq.selenium:selenium-java:4.28.1')

//    implementation group: 'org.seleniumhq.selenium:selenium-java:4.28.1'

    implementation group: 'org.hamcrest', name: 'hamcrest', version: '3.0'

    implementation group: 'org.testng', name: 'testng', version: '7.11.0'
    testImplementation(group: 'org.testng', name: 'testng', version: '7.11.0')

}

//task testGroups (type: Test)
test {
    useTestNG() {
        suites 'src/test/resources/gfgdfg'
    }
//    if (project.hasProperty('browser')) {
//        systemProperty 'browser', "${browser}"
//    }

    testLogging {
        events "passed", "skipped", "failed"
    }

}


