package ru.stqa.ent.shop.tests;// Generated by Selenium IDE
import com.tngtech.junit.dataprovider.DataProvider;
import org.junit.Assert;
import org.junit.Test;
import org.junit.jupiter.api.Disabled;
import org.junit.runners.Parameterized;
import org.openqa.selenium.By;
import ru.stqa.ent.shop.model.Carts;
import ru.stqa.ent.shop.model.RecipientForm;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.MatcherAssert.assertThat;

public class AddToCartTest extends TestBase {

  @DataProvider
  public Iterator<Object[]> validRecip() {
    List <Object[]> list = new ArrayList<Object[]>();
    list.add(new Object[] {"password1", "email1"});
    list.add(new Object[] {"password2", "email2"});
    list.add(new Object[] {"password3", "email3"});
    return list.iterator();
  }

  @Parameterized.BeforeParam


  @Test // Для TestNG (dataProvider = "data-provider")
  public void testAddToCart(String password, String email) throws InterruptedException { //параметры передать внутрь вместо имеющихся

    app.getNavigationHelper().gotoCart();

    int before = app.getCartHelper().getCartCount();
    app.getNavigationHelper().gotoMainPage();
    Thread.sleep(1000);
    app.getClickHelper().selectItemBox("//div[2]/div/div[2]/div[3]/div[2]/input");   //input[@value='Add to cart']
    if (app.getCartHelper().isThereAnElement("recipient-name")) {
    app.getEmailPasswordHelper().fillRecipientForm(new RecipientForm("name1", "name1@mail.ru"));
    app.getClickHelper().clickAddToCart(); }
    app.getNavigationHelper().gotoCart();
    int after = app.getCartHelper().getCartCount();
    Assert.assertEquals(after, before + 1);
  }

  @Disabled ("invalid method")
  public void testBadAddToCart() throws InterruptedException {

    app.getNavigationHelper().gotoCart();

    Carts before = app.getCartHelper().all();
    app.getNavigationHelper().gotoMainPage();
    Thread.sleep(1000);
    app.getClickHelper().selectItemBox("//div[2]/div/div[2]/div[3]/div[2]/input");   //input[@value='Add to cart']
    if (app.getCartHelper().isThereAnElement("recipient-name")) {
      app.getEmailPasswordHelper().fillRecipientForm(new RecipientForm("name1", "name1"));
      app.getClickHelper().clickAddToCart(); }
    app.getNavigationHelper().gotoCart();
    //хеширование - более быстрая предварительная проверка перед основной, на случай если тест упадет сразу на ней
    assertThat(app.getCartHelper().getCartCount(), equalTo(before.size()));

    Carts after = app.getCartHelper().all();
    assertThat(after, equalTo(before));
  }






  // Для того чтобы не передавать в функцию миллион параметров, если форма большая, можно их объединить в один объект,
  // который будет иметь много атрибутов (то есть вспомогательный класс, который описывает объекты типа "группа1" и туда пихать их атрибуты,
  // второй для "группа2" и тд; но в метод будет передаваться один объект) - RecipientForm


}
