package ru.stqa.ent.shop.tests;// Generated by Selenium IDE
import org.junit.Test;
import ru.stqa.ent.shop.model.RecipientForm;

public class AddToCartTest extends TestBase {

  @Test
  public void testAddToCart() throws InterruptedException {

    app.getClickHelper().selectItemBox();
    Thread.sleep(1000);
    app.getClickHelper().clickAddToCard();
    app.getEmailPasswordHelper().fillRecipientForm(new RecipientForm("name1", "name1@mail.ru"));
    app.getClickHelper().clickAddToCard();
    app.getNavigationHelper().gotoCart();
  }

  // Для того чтобы не передавать в функцию миллион параметров, если форма большая, можно их объединить в один объект,
  // который будет иметь много атрибутов (то есть вспомогательный класс, который описывает объекты типа "группа1" и туда пихать их атрибуты,
  // второй для "группа2" и тд; но в метод будет передаваться один объект) - RecipientForm


}
