package ru.stqa.ent.shop.tests;// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import ru.stqa.ent.shop.model.CartData;
import ru.stqa.ent.shop.model.RecipientForm;
import java.util.List;

public class CartTotalPrice extends TestBase {

  @Test
  public void testCartTotalPrice() throws InterruptedException {

    // Надо чтобы для каждого товара в корзине считалась правильная общая сумма
    app.getNavigationHelper().gotoCart();
    List<CartData> before = app.getCartHelper().getCartList();
//    app.getNavigationHelper().gotoMainPage();
//    Thread.sleep(1000);
//    app.getClickHelper().selectItemBox("//div[2]/div/div[2]/div[3]/div[2]/input");   //input[@value='Add to cart']
//    if (app.getCartHelper().isThereAnElement("recipient-name")) {
//    app.getEmailPasswordHelper().fillRecipientForm(new RecipientForm("name1", "name1@mail.ru"));
//    app.getClickHelper().clickAddToCard(); }
//    app.getNavigationHelper().gotoCart();
    List<CartData> after = app.getCartHelper().getCartList();
    Assert.assertEquals(after.size(), before.size() + 1);
  }




  // Для того чтобы не передавать в функцию миллион параметров, если форма большая, можно их объединить в один объект,
  // который будет иметь много атрибутов (то есть вспомогательный класс, который описывает объекты типа "группа1" и туда пихать их атрибуты,
  // второй для "группа2" и тд; но в метод будет передаваться один объект) - RecipientForm


}
