package ru.stqa.ent.shop.tests;// Generated by Selenium IDE
import org.hamcrest.CoreMatchers;
import org.hamcrest.MatcherAssert;
import org.junit.Assert;
import org.junit.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.runners.Parameterized;
import org.openqa.selenium.By;

import static org.hamcrest.CoreMatchers.*;
import static org.hamcrest.MatcherAssert.*;

public class CartChangeQty extends TestBase {

  @Test
  public void testCartChangeQuantity() throws InterruptedException {

    // Надо еще тест, чтобы для каждого товара в корзине считалась правильная общая сумма
    app.getNavigationHelper().gotoCart();
    if (!app.getCartHelper().isThereAnItem()) {
      app.getCartHelper().addCartItem("/html/body/div[4]/div[1]/div[4]/div[3]/div/div/div[3]/div[3]/div/div[2]/div[3]/div[2]/input");
    }
//    List<CartData> before = app.getCartHelper().getQtytList();
//    String totalqty = before.toString();
    int qtybefore = app.getCartHelper().getCartItemQty1("/html/body/div[4]/div[1]/div[4]/div/div/div[2]/div/form/table/tbody/tr[1]/td[5]/input");
    String beforestring = String.valueOf(qtybefore + 1);
    System.out.println(beforestring);
    app.getClickHelper().type(By.className("qty-input"), beforestring);
    app.getClickHelper().clickUpdateButton();
    int qtyafter = app.getCartHelper().getCartItemQty1("/html/body/div[4]/div[1]/div[4]/div/div/div[2]/div/form/table/tbody/tr[1]/td[5]/input");
//    List<CartData> after = app.getCartHelper().getQtytList();
//    Assert.assertEquals(qtybefore + 1, qtyafter);
    assertThat(qtybefore + 1, equalTo(qtyafter));  //проверялка из Hamcrest//
  }




  // Для того чтобы не передавать в функцию миллион параметров, если форма большая, можно их объединить в один объект,
  // который будет иметь много атрибутов (то есть вспомогательный класс, который описывает объекты типа "группа1" и туда пихать их атрибуты,
  // второй для "группа2" и тд; но в метод будет передаваться один объект) - RecipientForm


}
