package ru.stqa.ent.shop.tests;// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import ru.stqa.ent.shop.model.CartData;
import ru.stqa.ent.shop.model.RecipientForm;
import java.util.List;

public class CartTotalPrice extends TestBase {

  @Test
  public void testCartTotalQuantity() throws InterruptedException {

    // Надо еще тест, чтобы для каждого товара в корзине считалась правильная общая сумма
    app.getNavigationHelper().gotoCart();
//    List<CartData> before = app.getCartHelper().getQtytList();
//    String totalqty = before.toString();
    int qtybefore = app.getCartHelper().getCartItemQty1();
    String beforestring = String.valueOf(qtybefore + 1);
    System.out.println(beforestring);
    app.getClickHelper().type(By.className("qty-input"), beforestring);
    app.getClickHelper().clickUpdateButton();
    int qtyafter = app.getCartHelper().getCartItemQty1();
//    List<CartData> after = app.getCartHelper().getQtytList();
    Assert.assertEquals(qtybefore + 1, qtyafter);
  }




  // Для того чтобы не передавать в функцию миллион параметров, если форма большая, можно их объединить в один объект,
  // который будет иметь много атрибутов (то есть вспомогательный класс, который описывает объекты типа "группа1" и туда пихать их атрибуты,
  // второй для "группа2" и тд; но в метод будет передаваться один объект) - RecipientForm


}
