package ru.stqa.ent.shop.tests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.jupiter.api.Disabled;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import ru.stqa.ent.shop.model.GiftcardData;
import ru.stqa.ent.shop.model.RecipientForm;

public class GiftcartTests extends TestBase {

  @Disabled
  public void testGiftCards() throws InterruptedException {
    app.getNavigationHelper().gotoMainPage();
    app.getClickHelper().click(By.linkText("Gift Cards"));
    app.getClickHelper().clickAddToCart();
    app.getEmailPasswordHelper().fillRecipientForm(new RecipientForm("name1", "name1@mail.ru"));
    app.getClickHelper().clickAddToCart();
    app.getNavigationHelper().gotoCart();
    GiftcardData giftcard = app.getGiftcardHelper().all().iterator().next();
    GiftcardData gcardInfroEditForm = app.getGiftcardHelper().gcardInfroEditForm(giftcard);
  }


}
