package ru.stqa.ent.shop.tests;// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;

public class PageViewTest extends TestBase {

  @Test
  public void pageView() {

    app.getClickHelper().click(By.linkText("Gift Cards"));
    app.getClickHelper().click(By.id("products-viewmode"));

    {
      WebElement dropdown = app.getNavigationHelper().getWebElementDropdown("products-viewmode");
      app.getClickHelper().clickDropdown("//option[. = 'List']");
    }

    app.getClickHelper().click(By.id("products-orderby"));

    {
      WebElement dropdown = app.getNavigationHelper().getWebElementDropdown("products-orderby");
      app.getClickHelper().clickDropdown("//option[. = 'Price: Low to High']");
    }

    app.getClickHelper().click(By.id("products-orderby"));

    {
      WebElement dropdown = app.getNavigationHelper().getWebElementDropdown(String.valueOf(By.id("products-orderby")));
      app.getClickHelper().clickDropdown("//option[. = 'Created on']");
    }

    app.getClickHelper().click(By.id("products-orderby"));

    {
      WebElement dropdown = app.getNavigationHelper().getWebElementDropdown(String.valueOf(By.id("products-orderby")));
      app.getClickHelper().clickDropdown("//option[. = 'Position']");
    }

    app.getClickHelper().click(By.id("products-orderby"));

    {
      WebElement dropdown = app.getNavigationHelper().getWebElementDropdown(String.valueOf(By.id("products-orderby")));
      app.getClickHelper().clickDropdown("//option[. = 'Name: Z to A']");
    }

    app.getClickHelper().click(By.id("products-viewmode"));

    {
      WebElement dropdown = app.getNavigationHelper().getWebElementDropdown(String.valueOf(By.id("products-viewmode")));
      app.getClickHelper().clickDropdown("//option[. = 'Grid']");
    }
  }


}
