package ru.stqa.ent.shop.tests;// Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.interactions.Actions;


public class RegistrationTest extends TestBase {

  @Test
  public void testRegistration() throws InterruptedException {
    Thread.sleep(1000);
//    System.out.println("driver.get()");

//    WebDriverWait wait = new WebDriverWait(driver, 30);
//    wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Регистрация")));
// click on the compose button as soon as the "compose" button is visible
    {
      WebElement element = app.getEmailPasswordHelper().driver.findElement(By.cssSelector("li:nth-child(4) > .ico-wishlist"));
      Actions builder = new Actions(app.getEmailPasswordHelper().driver);
      builder.moveToElement(element).perform();
    }
    app.clickRegistration();
    app.chooseGender();
    app.getEmailPasswordHelper().fillNameLastname("nastia121", "nastia211");
    app.getEmailPasswordHelper().fillEmail("exampleemail11@mail.ru");
    app.getEmailPasswordHelper().fillConfirmPassword("123098");
    app.clickRegisterButton();
  }

}
