package ru.stqa.ent.shop.tests;// Generated by Selenium IDE
import org.junit.Test;

public class ZeroQuantityCartTest extends TestBase {

  @Test
  public void testZeroQuantityCart() {
    app.gotoCart();
    app.clickEditButton();
    app.changeQuantity("2");
    app.clickUpdateButton();
    app.gotoCart();
    app.chagneQuantity("0");
  }

}
