package ru.stqa.ent.shop.tests;// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.By;

public class ZeroQuantityCartTest extends TestBase {

  @Test
  public void testZeroQuantityCart() throws InterruptedException {
    app.getNavigationHelper().gotoCart();
    int before = app.getCartHelper().getCartCount();
    if (! app.getCartHelper().isThereAnItem()) {
      app.getCartHelper().addCartItem("/html/body/div[4]/div[1]/div[4]/div[3]/div/div/div[3]/div[3]/div/div[2]/div[3]/div[2]/input");
    }
    if (! app.getClickHelper().isThereEditButton()) {
      app.getClickHelper().click(By.className("product-name")); }
    else {
      app.getClickHelper().clickEditButton(); }
    app.getFieldRedactorHelper().changeQuantity("3");
    Thread.sleep(1000);
    app.getClickHelper().clickUpdateButton();
    app.getNavigationHelper().gotoCart();
    app.getFieldRedactorHelper().changeQuantity("1");
    int after = app.getCartHelper().getCartCount();
    Assert.assertEquals(after, before);
  }

}
