package ru.stqa.ent.shop;// Generated by Selenium IDE
import org.junit.Test;

public class AddToCartTest extends TestBase {

  @Test
  public void testAddToCart() throws InterruptedException {

    selectItemBox();
    Thread.sleep(1000);
    clickAddToCard();
    fillRecipientForm(new RecipientForm("name1", "name1@mail.ru"));
    clickAddToCard();
    gotoCart();
  }

  // Для того чтобы не передавать в функцию миллион параметров, если форма большая, можно их объединить в один объект,
  // который будет иметь много атрибутов (то есть вспомогательный класс, который описывает объекты типа "группа1" и туда пихать их атрибуты,
  // второй для "группа2" и тд; но в метод будет передаваться один объект) - RecipientForm


}
