package ru.stqa.ent.shop;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class AddToCartTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() throws InterruptedException {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();

    driver.get("https://demowebshop.tricentis.com/");
    driver.manage().window().setSize(new Dimension(1265, 1380));
    driver.findElement(By.linkText("Log in")).click();
    driver.findElement(By.id("Email")).sendKeys("exampleemail11@mail.ru");
    driver.findElement(By.id("Password")).click();
    driver.findElement(By.id("Password")).sendKeys("123098");
    driver.findElement(By.cssSelector(".login-button")).click();
    Thread.sleep(1000);

  }

  @After
  public void tearDown() {
    driver.quit();
  }
  
  @Test
  public void testAddToCart() throws InterruptedException {

    driver.findElement(By.cssSelector(".item-box:nth-child(2) .button-2")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("add-to-cart-button-2")).click();
    driver.findElement(By.id("giftcard_2_RecipientName")).click();
    driver.findElement(By.id("giftcard_2_RecipientName")).sendKeys("name1");
    driver.findElement(By.id("giftcard_2_RecipientEmail")).click();
    driver.findElement(By.id("giftcard_2_RecipientEmail")).sendKeys("name1@mail.ru");
    driver.findElement(By.id("add-to-cart-button-2")).click();
    driver.findElement(By.cssSelector(".ico-cart > .cart-label")).click();
  }
}
