package ru.stqa.ent.shop;// Generated by Selenium IDE
import org.junit.jupiter.api.Test;

public class LoginTest extends TestBase {

  @Test
  public void testLogin() {
    clickLogIn();
    fillEmailogin();
    fillPasswordlogin();
    submitLogin();
  }

}
