package ru.stqa.ent.shop;// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;


public class RegistrationTest2 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registrationTest() {
    // Test name: RegistrationTest2
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("http://shop.bugred.ru/");
    // 2 | setWindowSize | 1265x1380 |  | 
    driver.manage().window().setSize(new Dimension(1265, 1380));
    // 3 | click | linkText=Регистрация |  | 
    driver.findElement(By.linkText("Регистрация")).click();
    // 4 | click | id=exampleInputName |  | 
    driver.findElement(By.id("exampleInputName")).click();
    // 5 | type | id=exampleInputName | testname679 | 
    driver.findElement(By.id("exampleInputName")).sendKeys("testname3679");
    // 6 | click | id=exampleInputEmail1 |  | 
    driver.findElement(By.id("exampleInputEmail1")).click();
    // 7 | type | id=exampleInputEmail1 | example@mail.ru | 
    driver.findElement(By.id("exampleInputEmail1")).sendKeys("example@mail.ru");
    // 8 | click | id=exampleInputPassword1 |  | 
    driver.findElement(By.id("exampleInputPassword1")).click();
    // 9 | type | id=exampleInputPassword1 | 123098 | 
    driver.findElement(By.id("exampleInputPassword1")).sendKeys("123098");
    // 10 | click | id=exampleInputPassword2 |  | 
    driver.findElement(By.id("exampleInputPassword2")).click();
    // 11 | type | id=exampleInputPassword2 | 123098 | 
    driver.findElement(By.id("exampleInputPassword2")).sendKeys("123098");
    // 12 | click | name=_csrf |  | 
    driver.findElement(By.name("_csrf")).click();
    // 13 | click | id=alertify-ok |  | 
    driver.findElement(By.id("alertify-ok")).click();
  }
}
