package ru.stqa.ent.shop;// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;

import java.util.*;

public class RegistrationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeMethod
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterMethod
  public void tearDown() {
    driver.quit();
  }

  @org.testng.annotations.Test
  public void registration() {
    driver.get("http://shop.bugred.ru/");
    driver.findElement(By.linkText("Регистрация")).click();
    driver.findElement(By.id("exampleInputName")).click();
    driver.findElement(By.id("exampleInputName")).sendKeys("testuser99");
    driver.findElement(By.id("exampleInputEmail1")).click();
    driver.findElement(By.id("exampleInputEmail1")).sendKeys("example@mail.ru");
    driver.findElement(By.id("exampleInputPassword1")).click();
    driver.findElement(By.id("exampleInputPassword1")).sendKeys("1234");
    driver.findElement(By.id("exampleInputPassword2")).click();
    driver.findElement(By.id("exampleInputPassword2")).sendKeys("1234");
    driver.findElement(By.name("_csrf")).click();
    driver.findElement(By.id("alertify-ok")).click();
  }
}
