package ru.stqa.ent.shop;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class ZeroQuantityCartTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("https://demowebshop.tricentis.com/cart");
    driver.manage().window().setSize(new Dimension(1265, 1380));
  }
  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void testZeroQuantityCart() {

    clickEditButton();
    changeQuantity("2");
    clickUpdateButton();
    gotoCart();
    chagneQuantity("0");
  }

  private void chagneQuantity(String quantity) {
    driver.findElement(By.cssSelector(".cart-item-row")).click();
    driver.findElement(By.name("itemquantity5054028")).sendKeys(quantity);
    driver.findElement(By.name("itemquantity5054028")).sendKeys(Keys.ENTER);
  }

  private void gotoCart() {
    driver.findElement(By.cssSelector(".ico-cart > .cart-label")).click();
  }

  private void clickUpdateButton() {
    driver.findElement(By.id("add-to-cart-button-2")).click();
  }

  private void changeQuantity(String quantity) {
    driver.findElement(By.id("addtocart_2_EnteredQuantity")).click();
    driver.findElement(By.id("addtocart_2_EnteredQuantity")).sendKeys(quantity);
  }

  private void clickEditButton() {
    driver.findElement(By.linkText("Edit")).click();
  }
}
