package ru.stqa.ent.shop;// Generated by Selenium IDE
import org.junit.Test;

public class ZeroQuantityCartTest extends TestBase {

  @Test
  public void testZeroQuantityCart() {
    gotoCart();
    clickEditButton();
    changeQuantity("2");
    clickUpdateButton();
    gotoCart();
    chagneQuantity("0");
  }

}
